version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
      - ./src/:/var/src/app
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
    stdin_open: true
    tty: true

